web:
  image: recipes/nginx
  ports:
    - "8080:80"
  volumes:
    - .:/var/www
    - ./config/vhost.conf:/etc/nginx/sites-enabled/vhost.conf
  links:
    - php
  privileged: true
php:
  image: recipes/php
  volumes:
    - ./config/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - .:/var/www
  links:
    - db
    - test_db
  privileged: true
db:
  image: sameersbn/mysql
  ports:
   - "33060:3306"
  volumes:
   - /var/lib/mysql
  environment:
   - DB_NAME=recipe
   - DB_USER=admin
   - DB_PASS=admin
test_db:
  image: sameersbn/mysql
  ports:
   - "33063:3306"
  volumes:
   - /var/lib/mysql
  environment:
   - DB_NAME=test_recipe
   - DB_USER=admin
   - DB_PASS=admin
