FROM nmcteam/php56
MAINTAINER Nigel Kirby <nigel.kirby on gmail.com>

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=bin --filename=composer
RUN alias composer='php bin/composer'

